### ISSUE TITLE
【UI】陣營牌視覺-潛伏、軍情、醬油

### ISSUE THREAD

**Issue by coral-tsai** [Game-as-a-Service/The-Message#32]
- [x] 潛伏
- [x] 軍情
- [x] 醬油

**Comment by coral-tsai** [comment]
![Image](https://github.com/Game-as-a-Service/The-Message/assets/26357238/4b5a755c-4615-459e-a4c4-faa22976b505)
![Image](https://github.com/Game-as-a-Service/The-Message/assets/26357238/be2f45c5-7934-44a1-b917-ba5d7fced72f)
![Image](https://github.com/Game-as-a-Service/The-Message/assets/26357238/147743c7-bc67-4646-9b1c-3602bf6c1b00)

**Comment by linycken013127** [comment]
sprint1 完成
