### ISSUE TITLE
【Frontend】完成初版「風聲遊戲」/ All Task List

### ISSUE THREAD

**Issue by ping-yee** [Game-as-a-Service/The-Message#77]
#### 狀態管理
- [ ] 【Frontend】卡牌動畫討論
- [ ] 【Frontend】全域卡牌狀態管理切分 (待討論)

#### 驗證
- [ ] 【Frontend】建立身分驗證機制/確認玩家身分並確認持有卡片

#### 動畫
- [ ] 【Frontend】玩家收牌動畫
- [ ] 【Frontend】玩家出牌動畫

#### API 串接
- [ ] 【Frontend】玩家收牌頁面連動串接
- [ ] 【Frontend】玩家出牌頁面連動串接

#### SSE
- [ ] 【Frontend】接收SSE事件並改動卡牌狀態

**Comment by yi-luan** [comment]
#87 
#89

**Comment by yi-luan** [comment]
【Frontend】建立身分驗證機制/確認玩家身分並確認持有卡片
【Frontend】全域卡牌狀態管理切分 (待討論)
【Frontend】玩家收牌動畫、玩家出牌動畫
【Frontend】接收SSE事件並改動卡牌狀態

**Comment by linycken013127** [comment]
sprint1 結束，先關閉
