### ISSUE TITLE
【Project Manage】完成初版「風聲遊戲」/ All Task List

### ISSUE THREAD

**Issue by ping-yee** [Game-as-a-Service/The-Message#80]
## Example Mapping

- [x] 攔截
- [x] 調虎離山

## Event Storming

- [x] Version 0.1 Release
- [ ] Version 1.0 Release

## OOA

- [ ] OOA 0.1 Release

## MD

- [ ] 遊戲介紹 Readme 撰寫出 version 1
- [ ] 開發操作 Readme 撰寫出 version 1

## 資源彙整

- [ ] GitHub Operation

**Comment by linycken013127** [comment]
sprint1 完成
